### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by ugintl** [NicolasMarqui/MarcaPonto#2]
1. How to install it?

2. Is it using a database?

**Comment by bmrocha** [comment]
Ola gostaria testar

**Comment by ugintl** [comment]
Yes. Also if you allow me, I want to use it for a client.

**Comment by NicolasMarqui** [comment]
Hey guys, i created this over a year ago for a college project, the code is pretty bad because i was a beginner and i didn't knew much about react and it's best practices...

I only did the frontend, the backend was made by a friend of mine, using Spring boot and postgres. Feel free to use it as you like, but i'm pretty sure not everything is working the way it's supposed to, since this was only created to work with one specific project.(Here’s the backend if someone wants to take a look: https://github.com/HeitorAmaral/ws-marcaponto-fatec-public)

I’ll probably re-do this in the future, using next, tailwind and node, but not right now because I have a lot of other projects to do.

Cheers and happy coding
